#!/usr/bin/env bash

set -o errexit
set -o nounset

worker_ready() {
    celery -A app.celery inspect ping
}

until worker_ready; do
  echo 'Waiting for Celery workers to be ready...' >&2
  sleep 1
done
echo 'Celery workers ready' >&2

celery -A app.celery  \
# Referencing an env variable here was not working
    --broker="redis://redis:6379/0" \
    flower \
    --port=5555
