"""Initial migration

Revision ID: 199ff59271e2
Revises: 
Create Date: 2023-02-02 05:55:06.435189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199ff59271e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=2047), nullable=False),
    sa.Column('input_options', sa.String(length=2047), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('tool',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=2047), nullable=False),
    sa.Column('url', sa.String(length=2047), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=80), nullable=False),
    sa.Column('field_name', sa.String(length=80), nullable=False),
    sa.Column('user', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['field_name'], ['field.name'], ),
    sa.ForeignKeyConstraint(['tool_name'], ['tool.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('tool')
    op.drop_table('field')
    # ### end Alembic commands ###
