"""Expand field table

Revision ID: 9a8f0bd6437a
Revises: 199ff59271e2
Create Date: 2023-02-10 05:06:47.221638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a8f0bd6437a'
down_revision = '199ff59271e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('field', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pattern', sa.String(length=320), nullable=True))
        batch_op.alter_column('input_options',
               existing_type=mysql.VARCHAR(length=2047),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('field', schema=None) as batch_op:
        batch_op.alter_column('input_options',
               existing_type=sa.JSON(),
               type_=mysql.VARCHAR(length=2047),
               existing_nullable=True)
        batch_op.drop_column('pattern')

    # ### end Alembic commands ###
