"""Add title field to completed_task

Revision ID: f0b0e9060a20
Revises: c92647a6aee1
Create Date: 2023-03-16 05:32:05.541331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0b0e9060a20'
down_revision = 'c92647a6aee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('completed_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tool_title', sa.String(length=255), nullable=False))
        batch_op.alter_column('tool_name',
               existing_type=sa.VARBINARY(length=255),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('field',
               existing_type=sa.VARBINARY(length=80),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('user',
               existing_type=sa.VARBINARY(length=255),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('field', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARBINARY(length=80),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARBINARY(length=2047),
               type_=sa.String(length=2047),
               existing_nullable=False)
        batch_op.alter_column('input_options',
               existing_type=sa.VARBINARY(length=2047),
               type_=sa.String(length=2047),
               existing_nullable=True)
        batch_op.alter_column('pattern',
               existing_type=sa.VARBINARY(length=320),
               type_=sa.String(length=320),
               existing_nullable=True)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('tool_name',
               existing_type=sa.VARBINARY(length=255),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('field_name',
               existing_type=sa.VARBINARY(length=80),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('user',
               existing_type=sa.VARBINARY(length=255),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARBINARY(length=255),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARBINARY(length=255),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.BLOB(),
               type_=sa.TEXT(length=65535),
               existing_nullable=False)
        batch_op.alter_column('url',
               existing_type=sa.VARBINARY(length=2047),
               type_=sa.String(length=2047),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.String(length=2047),
               type_=sa.VARBINARY(length=2047),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(length=65535),
               type_=sa.BLOB(),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=sa.VARBINARY(length=255),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=sa.VARBINARY(length=255),
               existing_nullable=False)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('user',
               existing_type=sa.String(length=255),
               type_=sa.VARBINARY(length=255),
               existing_nullable=True)
        batch_op.alter_column('field_name',
               existing_type=sa.String(length=80),
               type_=sa.VARBINARY(length=80),
               existing_nullable=False)
        batch_op.alter_column('tool_name',
               existing_type=sa.String(length=255),
               type_=sa.VARBINARY(length=255),
               existing_nullable=False)

    with op.batch_alter_table('field', schema=None) as batch_op:
        batch_op.alter_column('pattern',
               existing_type=sa.String(length=320),
               type_=sa.VARBINARY(length=320),
               existing_nullable=True)
        batch_op.alter_column('input_options',
               existing_type=sa.String(length=2047),
               type_=sa.VARBINARY(length=2047),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=2047),
               type_=sa.VARBINARY(length=2047),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=80),
               type_=sa.VARBINARY(length=80),
               existing_nullable=False)

    with op.batch_alter_table('completed_task', schema=None) as batch_op:
        batch_op.alter_column('user',
               existing_type=sa.String(length=255),
               type_=sa.VARBINARY(length=255),
               existing_nullable=False)
        batch_op.alter_column('field',
               existing_type=sa.String(length=80),
               type_=sa.VARBINARY(length=80),
               existing_nullable=False)
        batch_op.alter_column('tool_name',
               existing_type=sa.String(length=255),
               type_=sa.VARBINARY(length=255),
               existing_nullable=False)
        batch_op.drop_column('tool_title')

    # ### end Alembic commands ###
