"""Initial migration

Revision ID: fa4597ad08b0
Revises: 
Create Date: 2023-02-13 19:58:06.844199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa4597ad08b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.TEXT(length=65535), nullable=False),
    sa.Column('url', sa.String(length=2047), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    mysql_charset='utf8mb4'
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('field_name', sa.String(length=80), nullable=False),
    sa.Column('user', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['field_name'], ['field.name'], ),
    sa.ForeignKeyConstraint(['tool_name'], ['tool.name'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('tool')
    # ### end Alembic commands ###
